- name: Deploy Helm chart
  hosts: all
  become: false

  tasks:
    - name: Upgrad Helm chart
      shell: |
        helm upgrade --install my-app {{ ansible_env.HOME }}/helm-deploy/full-stack-project/helm/my-app
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
