- name: Setup Minikube and Helm
  hosts: all
  become: true  

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - curl
        - docker.io
        - conntrack
        - apt-transport-https
        - ca-certificates
        - gnupg
        - lsb-release

    - name: Enable and start Docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Install kubectl
      shell: |
        bash -c 'VERSION=$(curl -s https://dl.k8s.io/release/stable.txt) && \
        curl -LO https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl && \
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl'
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Start Minikube
      become: true
      shell: |
        minikube start --driver=docker
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"
        HOME: "{{ ansible_env.HOME }}"

