name: Deploy helm charts into minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend Docker image
        run: docker build -t nekoreec/frontend:latest .
        working-directory: ./UI/azure_manager
          
      - name: Push frontend to Docker hub
        run: docker push nekoreec/frontend:latest

      - name: Build backend Docker image
        run: docker build -t nekoreec/backend:latest .
        working-directory: ./backend

      - name: Push backend to Docker hub
        run: docker push nekoreec/backend:latest

  setup-and-deploy:
    name: Setup minicube via ansible
    runs-on: ubuntu-latest
    steps: 
          - name: Checkout code
            uses: actions/checkout@v3 
    




          


      
