name: Deploy helm charts into minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend Docker image
        run: docker build -t nekoreec/frontend:latest .
        working-directory: ./UI/azure_manager
          
      - name: Push frontend to Docker hub
        run: docker push nekoreec/frontend:latest

      - name: Build backend Docker image
        run: docker build -t nekoreec/backend:latest .
        working-directory: ./backend

      - name: Push backend to Docker hub
        run: docker push nekoreec/backend:latest


  Helm deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH key
        run: | 
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create inventory file
        run: |
          echo "[azure]" > ansible/inventory.ini
          echo "${{ secrets.PUBLIC_IP }} ansible_user=${{ secrets.SSH_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini
          cat ansible/inventory.ini

      - name: Set up ansible
        run: sudo apt update && sudo apt install -y ansible sshpass

      

    deploy:
      name: deploy
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Configure Azure VM
          run: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i ansible/inventory.ini ansible/ansible.setup.yml
    




          


      
