name: CI/CD pipline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub log in
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        run: |
          docker build -t nekoreec/frontend:latest .
          docker push nekoreec/frontend:latest
        working-directory: ./UI/azure_manager

      - name: Build and push backend
        run: |
          docker build -t nekoreec/backend:latest .
          docker push nekoreec/backend:latest
        working-directory: ./backend

      - name: Upload helm and playbooks
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: |
            full-stack-project/helm/
            ansible/

  prepare-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible to set up Minikube
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook ansible/setup_minikube.yml -i "${{ secrets.VM_HOST }}," -u ${{ secrets.SSH_USER }} --private-key ~/.ssh/id_rsa

  deploy-helm:
    runs-on: ubuntu-latest
    needs: [build-and-push, prepare-vm]

    steps:
      - name: Download deploy files
        uses: actions/download-artifact@v4
        with:
          name: deploy-files
          path: deploy/

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Helm deploy via Ansible
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook ansible/deploy_helm.yml -i "${{ secrets.VM_HOST }}," -u ${{ secrets.SSH_USER }} --private-key ~/.ssh/id_rsa
